config/routes.rb
Rails.application.routes.draw do
  # get 'users/:id', to: 'users#show'

  resources :ngos do
      resources :donations, only: ['new', 'create', 'update', 'patch']
      resources :conversations do
        resources :messages
      end
  end


  devise_for :users, controllers: {
  sessions: 'users/sessions',
  omniauth_callbacks: 'users/omniauth_callbacks'
  }

  get 'users/:id', to: 'users#show'

  root to: 'ngos#index'

  resources :conversations do
    resources :messages
  end

  get 'users/conversations/:id', controller: 'conversations', action: 'show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'ngos/:id/dashboard', to: 'ngos#dashboard'
  get 'ngos/:id/unauthorized', to: 'ngos#unauthorized'
end

app/models/ngo.rb
class Ngo < ApplicationRecord
  has_many :ngo_types
  has_many :types, through: :ngo_types
  has_many :donations
  has_many :conversations
  has_many :users, dependent: :nullify

  validates :name, presence: true
  validates :address, presence: true

  include PgSearch
  pg_search_scope :search_by_name_and_address, against: [ :name, :address ]

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

end

app/models/ngo_type.rb
class NgoType < ApplicationRecord
  belongs_to :ngo
  belongs_to :type

  validates_uniqueness_of :ngo, scope: :type
  validates_presence_of :ngo, scope: :type
end

app/controllers/ngos_controller.rb
class NgosController < ApplicationController
  def new
    @user = current_user
    @ngo = Ngo.new
  end

  def create
    @user = current_user
    @ngo = Ngo.new(ngo_params)

    types = params[:ngo][:type_ids]
    size = params[:ngo][:type_ids].size

    if @ngo.save
      @user.update(ngo_id: @ngo.id)

      (1...size).each do |t|
        a = NgoType.create(ngo_id: @ngo.id, type_id: types[t])
      end

      redirect_to controller: "ngos", action: "dashboard", id: "#{@ngo.id}"
    else
      render :new
    end
  end

  def index
    if params[:query]
      @ngos = Ngo.search_by_name_and_address(params[:query])
    elsif params[:type]
      @ngos = Ngo.includes(:types).where(:types => {name: params[:type]})
    else
      @ngos = Ngo.all
    end

    @hash = Gmaps4rails.build_markers(@ngos) do |ngo, marker|
      marker.lat ngo.latitude
      marker.lng ngo.longitude
      # marker.picture ({ url: "https://i.imgur.com/B0Q6ghF.png"})
    end
  end

  def show
    @ngo = Ngo.find(params[:id])
    @donation = Donation.new

    @hash = Gmaps4rails.build_markers(@ngo) do |ngo, marker|
      marker.lat ngo.latitude
      marker.lng ngo.longitude
    end
  end

  def dashboard
    # if current_user.ngo_id.to_s == params[:id]
      @user = current_user
      @ngo = Ngo.find(params[:id])
      @donations = @ngo.donations.reverse
      @users =[]

      @donations.each do |d|
        @users.push(User.find(d.user_id))
      end

      @users = @users.uniq.compact
    # else
    #   redirect_to controller: 'ngos', action: 'unauthorized', id: params[:id]
    # end
  end

  def unauthorized
    @user = current_user
    @ngo = Ngo.find(params[:id])
  end

  def destroy
    ngo = Ngo.find(params[:id])
    ngo.destroy
    redirect_to controller: 'users', action: 'show', id: current_user.id
  end

  private

  def ngo_params
    params.require(:ngo).permit(:user_id, :photo, :name, :address, :lat, :lng)
  end
end

app/views/ngos/dashboard.html.erb
<% javascript_include_tag "user" %>

<div class="prfl-page">
  <div class="container">
    <div class="profile">
      <% if @ngo.photo %>
        <% avatar_url = @ngo.photo.gsub('square', 'large') %>
      <% else %>
        <% avatar_url = "http://placehold.it/200x200"%>
      <% end %>
      <div class="you">
          <h3>Your NGO:</h3>
      <div class="selfy">
        <%= image_tag avatar_url, class: 'profile-img' %>


        <h4> <%= @ngo.name %> </h4>
        <%= button_to "Delete NGO", { controller: "ngos", action: "destroy" }, method: :delete, class: "btn btn-danger" %>
      </div>
      </div>

      <div class="messages">
        <h3>Messages:</h3>
        <table class="table">
        <% @users.each_with_index do |user, index| %>
            <tr>
              <td><%= index +=1 %></td>
              <td><%= user.first_name %> <%= user.last_name %></td>
              <td>
                <%= link_to "Send Message", "#", class: "btn btn-success btn-xs start-conversation",
                            "data-uid" => user.id, "data-nid" => @ngo.id %>
              </td>
            </tr>
        <% end %>
      </table>
      </div>

      <div class="big donations">
        <h3>Your donators:</h3>
        <div class="list">
          <% @donations.each do |d| %>
          <div class="card">
            <div class="card-body">
              <div class="content">
                <h4><%= d.user.first_name %></h4>
                <p><%= d.items %></p>
                <p><%= d.created_at %></p>
              </div>
              <%= image_tag("icons/#{Type.find(d.type_id).name.downcase}.png", class: "type") %>
              <%= button_to "Accept", 'donations#accept', class: "btn btn-success" %>
              <%= button_to "Reject", 'donations#reject', class: "btn btn-warning" %>
            </div>

            <% case d.status  %>
            <% when 'done' %>
              <% notice = " done"  %>
            <% when 'failed' %>
              <% notice = " failed"  %>
            <% else %>
                <% notice = ' ' %>
            <% end %>

            <div class="card-notice<%= notice %>">

            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/ngos/index.html.erb
<%= content_for :title, "radar" %>
<!-- banner -->

<div class="homepage-banner" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.1) 0%, rgba(0,0,0,0.3) 50%), url('http://ww2.kqed.org/bayareabites/wp-content/uploads/sites/24/2015/11/BAB-SF-Food-bank-1440x960.jpg');">
  <div class="banner-content">
    <h1>Find an organization to donate to</h1>
  <!-- map -->
    <div class="container">
      <div>
        <%= render 'shared/searchbar' %>
      </div>
    </div>
  </div>
</div>

<div class="banner-icons">
  <%= link_to ngos_path(type: "Books"), class: "filter-icon" do %>
    <div class="banner-icons-type grow <%= params[:type]=='Books' ? 'active': ''  %>"><%= image_tag("icons/books_200.png", :width=>50, :crop=>"fill", id: "books") %>
      <p class="hider">Books</p>
    </div>
  <% end %>
  <%= link_to ngos_path(:type => "Bycicles"), class: "filter-icon" do %>
    <div class="banner-icons-type grow <%= params[:type]=='Bycicles' ? 'active': ''  %>"><%= image_tag("icons/bicycles_200.png", :width=>50, :crop=>"fill", id: "bycicles") %></div>
      <p class="hider">Bicycles</p>
  <% end %>
  <%= link_to ngos_path(:type => "Clothes"), class: "filter-icon" do %>
    <div class="banner-icons-type grow <%= params[:type]=='Clothes' ? 'active': ''  %>"><%= image_tag("icons/clothes_200.png", :width=>50, :crop=>"fill", id: "clothes") %></div>
      <p class="hider">Clothes</p>
  <% end %>
  <%= link_to ngos_path(:type => "Furniture"), class: "filter-icon" do %>
    <div class="banner-icons-type grow <%= params[:type]=='Furniture' ? 'active': ''  %>"><%= image_tag("icons/furniture_200.png", :width=>50, :crop=>"fill", id: "furniture") %></div>
      <p class="hider">Furniture</p>
  <% end %>
  <%= link_to ngos_path(:type => "Food"), class: "filter-icon" do %>
    <div class="banner-icons-type grow <%= params[:type]=='Food' ? 'active': ''  %>"><%= image_tag("icons/food_200.png", :width=>50, :crop=>"fill", id: "food") %></div>
      <p class="hider">Food</p>
  <% end %>
  <%= link_to ngos_path(:type => "Electronics"), class: "filter-icon" do %>
  <div class="banner-icons-type grow <%= params[:type]=='Electronics' ? 'active': ''  %>"><%= image_tag("icons/electronics_200.png", :width=>50, :crop=>"fill", id: "electronics") %></div>
      <p class="hider">Electronics</p>
  <% end %>
  <%= link_to ngos_path(:type => "Other"), class: "filter-icon" do %>
  <div class="banner-icons-type grow <%= params[:type]=='Other' ? 'active': ''  %>"><%= image_tag("icons/other_200.png", :width=>50, :crop=>"fill", id: "other") %></div>
      <p class="hider">Other</p>
  <% end %>
</div>

<div id="results" class="main-index-container">
  <%= render 'shared/card' %>
  <%= render 'shared/map' %>
</div>

app/views/ngos/new.html.erb
<% content_for :title, "Create an NGO" %>

<div class="container">
 <div class="box" style="margin-top: 50px;">
  <h2>Register your NGO</h2>
  <br>
  <%= simple_form_for [@ngo] do |f|  %>
  <%= f.input :name  %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.association :types, label_method: :name, value_method: :id, as: :check_boxes, label: false,  item_wrapper_class: "checkbox-inline" %>
  <%= f.input :photo, placeholder: "url" %>
  <%= f.submit %>
  <% end %>
  </div>
</div>

app/views/ngos/show.html.erb
<% content_for :title, "#{@ngo.name} | radar" %>

<!-- #ngo title -->
<div class="ngo-show-page">
  <div class="container">

    <%= render 'shared/ngo_banner' %>
    <div class="grid-container">
      <div class="grid">
        <div class="description">
          <p><b>Who we are:</b></p>
          <p><b><%= @ngo.name %></b></p>
          <p><%= @ngo.address.capitalize %></p>
          <hr class = "border-line"/>
          <p><b>Who we help:</b></p>
          <p><%= @ngo.description %></p>
        </div>

        <div class="ngo-icons">

          <p><b>What we're looking for:</b></p>
          <div class="icon-box">

            <% @ngo.types.each do |type| %>
            <div class="ngo-icon-item" class="text-center">
              <%= image_tag("icons/#{type.name.downcase}.png", :width=>50, :crop=>"fill", class: "text-center") %>
              <p id="ngo-icon-name"><%= "#{type.name.downcase}" %></p>
            </div>
            <% end %>

          </div>

          <hr class = "border-line"/>

          <p><b>Our history:</b></p>
          <p><%= @ngo.description %></p>

        </div>



        <div class="ngo-donate">
          <div class="text-center">
            <p>Make your donation here <%= current_user.first_name.nil? ? ": " : ", " + current_user.first_name unless current_user.nil? %></p>
            <div class="row">
              <div class="donate-form form-group">

              <%= render 'shared/ngo_show_donation_form' %>

              </div>
            </div>
          </div>
        </div>



        <div class="ngo-map">
          <%= render 'shared/ngo_show_map' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/ngos/unauthorized.html.erb
<% content_for :title, "Unauthorized" %>
<div class="content" style="display: flex; justify-content: center; align-items: center; height: 50vh;">
  <center>
    <i style="font-size: 200px;" class="fa fa-ban fa-6" aria-hidden="true"></i>
    <h2>You can't access that ngo</h2>
  </center>
  <%= button_to  %>
</div>