config/routes.rb
Rails.application.routes.draw do
  # get 'users/:id', to: 'users#show'

  resources :ngos do
      resources :donations, only: ['new', 'create', 'update', 'patch']
      resources :conversations do
        resources :messages
      end
  end


  devise_for :users, controllers: {
  sessions: 'users/sessions',
  omniauth_callbacks: 'users/omniauth_callbacks'
  }

  get 'users/:id', to: 'users#show'

  root to: 'ngos#index'

  resources :conversations do
    resources :messages
  end

  get 'users/conversations/:id', controller: 'conversations', action: 'show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'ngos/:id/dashboard', to: 'ngos#dashboard'
  get 'ngos/:id/unauthorized', to: 'ngos#unauthorized'
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :user
  belongs_to :ngo

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :user_id, scope: :ngo_id

  # This was in the documentation. Doesn't make a lot of sense right now
  # with different user models (ngo and user)

  scope :involving, -> (user) do
    where("conversations.user_id =?", user.id)
  end

  scope :involving, -> (ngo) do
    where("conversations.ngo_id =?", ngo.id)
  end

  scope :between, -> (user, ngo) do
    where("(conversations.user_id = ? AND conversations.ngo_id =?)", user, ngo)
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  layout false

  def create
    if Conversation.between(params[:user_id], params[:ngo_id]).present?
      @conversation = Conversation.between(params[:user_id], params[:ngo_id])
    else
      @conversation = Conversation.create!(conversation_params)
    end

    render json: { conversation_id: @conversation.ids[0] }
  end

  def show
    @conversation = Conversation.find(params[:id])
    @receiver = interlocutor(@conversation)
    @receiver.class.to_s.downcase == "ngo" ? @sender = @conversation.user : @sender = @conversation.ngo
    @messages = @conversation.messages
    @message = Message.new
  end

  private
    def conversation_params
      params.permit(:user_id, :ngo_id)
    end

    def interlocutor(conversation)
      if params[:ngo_id].nil?
        conversation.user
      else
        conversation.ngo
      end
    end
end

app/views/conversations/show.html.erb
<div class="chatboxhead">
  <div class="chatboxtitle">
    <i class="fa fa-comments"></i>

    <h1><%= @receiver.class.to_s.downcase == 'user' ? @sender.name : @sender.first_name %> </h1>
  </div>
  <div class="chatboxoptions">
    <%= link_to "<i class='fa  fa-minus'></i> ".html_safe, "#", class: "toggleChatBox", "data-cid" => @conversation.id %>
    &nbsp;&nbsp;
    <%= link_to "<i class='fa  fa-times'></i> ".html_safe, "#", class: "closeChat", "data-cid" => @conversation.id %>
  </div>
  <br clear="all"/>
</div>
<div class="chatboxcontent">
  <% if @messages.any? %>
      <%= render @messages, locals: { receiver: @receiver } %>
  <% end %>
</div>
<div class="chatboxinput">
  <%= form_for([@conversation, @message], :remote => true, :html => {id: "conversation_form_#{@conversation.id}"}) do |f| %>
      <%= f.text_area :body, class: "chatboxtextarea", "data-cid" => @conversation.id %>
      <%= f.hidden_field(:sender, value: @receiver.class.to_s.downcase) %>
  <% end %>
</div>

<%= subscribe_to conversation_path(@conversation) %>