config/routes.rb
Rails.application.routes.draw do
  # get 'users/:id', to: 'users#show'

  resources :ngos do
      resources :donations, only: ['new', 'create', 'update', 'patch']
      resources :conversations do
        resources :messages
      end
  end


  devise_for :users, controllers: {
  sessions: 'users/sessions',
  omniauth_callbacks: 'users/omniauth_callbacks'
  }

  get 'users/:id', to: 'users#show'

  root to: 'ngos#index'

  resources :conversations do
    resources :messages
  end

  get 'users/conversations/:id', controller: 'conversations', action: 'show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'ngos/:id/dashboard', to: 'ngos#dashboard'
  get 'ngos/:id/unauthorized', to: 'ngos#unauthorized'
end

app/views/shared/_card.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <% @ngos.each do |ngo| %>

        <% unless ngo.photo.nil? %>
          <% photo_url = image_path ngo.photo %>
        <% else %>
          <% photo_url = "http://res.cloudinary.com/dsmei8zni/image/upload/v1510934787/default.jpg" %>
        <% end %>

      <% string = "card " %>
      <% ngo.types.each do |type| %>
      <% string += type.name.downcase + " " %>
      <% end %>

      <%= link_to ngo_path(id: ngo.id) do %>

      <div class="<%= string %>">
        <div class="card-image" style="background-image: url('<%= photo_url %>')">
        </div>
        <div class="card-content">
          <h5><%= ngo.name.upcase %></h5>
          <p><%= ngo.description %>
          </div>
          <div class="card-footer">
            <% ngo.types.each do |t| %>
            <%= image_tag("icons/#{t.name.downcase}.png") %>
            <% end %>
          </div>
        </div>
        <% end %>

        <% end %>

      </div>
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_homepagecard.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <% @ngos.each do |ngo| %>
      <% # if ngo.photos.nill? %>
      <% photo_url = image_path 'card_default.jpg' %>

      <% # else %>

      <% #photo_url = cl_image_path ngos.photos.first.path, height: 500, width: 400, crop: :fit  %>
      <% #end %>

      <%= link_to ngo_path(id: ngo.id) do %>
      <div class="card" style="background-image: url('<%= photo_url %>')">
        <div class="card-description">
          <%= ngo.name.upcase %>
        </div>
      </div>
      <% end %>

      <% end %>

    </div>
  </div>
</div>

app/views/shared/_map.html.erb
<div id="map"></div>


<% content_for(:after_js) do %>
  <%= javascript_tag do %>
      styles = [
             {
                 "featureType": "all",
                 "elementType": "labels.text.fill",
                 "stylers": [
                     {
                         "saturation": 36
                     },
                     {
                         "color": "#333333"
                     },
                     {
                         "lightness": 40
                     }
                 ]
             },
             {
                 "featureType": "all",
                 "elementType": "labels.text.stroke",
                 "stylers": [
                     {
                         "visibility": "on"
                     },
                     {
                         "color": "#ffffff"
                     },
                     {
                         "lightness": 16
                     }
                 ]
             },
             {
                 "featureType": "all",
                 "elementType": "labels.icon",
                 "stylers": [
                     {
                         "visibility": "off"
                     }
                 ]
             },
             {
                 "featureType": "administrative",
                 "elementType": "geometry.fill",
                 "stylers": [
                     {
                         "color": "#fefefe"
                     },
                     {
                         "lightness": 20
                     }
                 ]
             },
             {
                 "featureType": "administrative",
                 "elementType": "geometry.stroke",
                 "stylers": [
                     {
                         "color": "#fefefe"
                     },
                     {
                         "lightness": 17
                     },
                     {
                         "weight": 1.2
                     }
                 ]
             },
             {
                 "featureType": "landscape",
                 "elementType": "geometry",
                 "stylers": [
                     {
                         "color": "#f5f5f5"
                     },
                     {
                         "lightness": 20
                     }
                 ]
             },
             {
                 "featureType": "poi",
                 "elementType": "geometry",
                 "stylers": [
                     {
                         "color": "#f5f5f5"
                     },
                   {
                       "lightness": 21
                   }
               ]
           },
             {
                 "featureType": "poi.park",
                 "elementType": "geometry",
                 "stylers": [
                     {
                         "color": "#dedede"
                     },
                     {
                         "lightness": 21
                     }
                 ]
             },
             {
                 "featureType": "road.highway",
                 "elementType": "geometry.fill",
                 "stylers": [
                     {
                         "color": "#ffffff"
                     },
                     {
                         "lightness": 17
                     }
                 ]
             },
             {
                 "featureType": "road.highway",
                 "elementType": "geometry.stroke",
                 "stylers": [
                     {
                         "color": "#ffffff"
                     },
                     {
                         "lightness": 29
                     },
                     {
                         "weight": 0.2
                     }
                 ]
             },
             {
                 "featureType": "road.arterial",
                 "elementType": "geometry",
                 "stylers": [
                     {
                         "color": "#ffffff"
                     },
                     {
                         "lightness": 18
                     }
                 ]
             },
             {
                 "featureType": "road.local",
                 "elementType": "geometry",
                 "stylers": [
                     {
                         "color": "#ffffff"
                     },
                     {
                         "lightness": 16
                     }
                 ]
             },
             {
                 "featureType": "transit",
                 "elementType": "geometry",
                 "stylers": [
                     {
                         "color": "#f2f2f2"
                     },
                     {
                         "lightness": 19
                     }
                 ]
             },
             {
                 "featureType": "water",
                 "elementType": "geometry",
                 "stylers": [
                     {
                         "color": "#e9e9e9"
                     },
                     {
                         "lightness": 17
                     }
                 ]
             },
             {
                 "featureType": "water",
                 "elementType": "geometry.fill",
                 "stylers": [
                     {
                         "saturation": "0"
                     },
                     {
                         "color": "#bab9b9"
                     }
                 ]
             }
         ]


    var handler = Gmaps.build('Google');

    var iconBase = 'http://res.cloudinary.com/dsmei8zni/image/upload/v1510754575/marker.png';


    handler.buildMap({
      internal: { id: 'map' }
    }, function() {
      markers = handler.addMarkers(<%= raw @hash.to_json %>);
      handler.bounds.extendWith(markers);

      handler.fitMapToBounds();

      if (markers.length == 0) {
        handler.getMap().setZoom(2);
      } else if (markers.length == 1) {
        handler.getMap().setZoom(14);
      }
    });
 <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <div class="logonav">
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= cl_image_tag "logo" %> radar
    <% end %>
  </div>

  <!-- Right Navigation -->

  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= render 'shared/searchbar_navbar' %>
    <% if user_signed_in? %>
      <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>

      <!-- Links when logged in -->
      <%= link_to "Donations", { controller: 'users', action: 'show', id: current_user.id }, class: "navbar-wagon-item navbar-wagon-link" %>

      <% if current_user.ngo_id.nil? %>
        <%= link_to "Register your NGO", { controller: 'ngos', action: 'new' }, class: "navbar-wagon-item navbar-wagon-link"%>
      <% else %>
        <%= link_to "Your NGO", { controller: 'ngos', action: 'dashboard', id: current_user.ngo_id }, class: "navbar-wagon-item navbar-wagon-link"%>
      <% end %>

    <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "/" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

      <!-- Dropdown list appearing on mobile only -->
      <div class="navbar-wagon-item hidden-md hidden-lg">
        <div class="dropdown">
          <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "/" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Settings") %>
              <% end %>
            </li>

            <li>
              <%= link_to "/" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Settings") %>
              <% end %>
            </li>

            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>
      <div class="navbar-wagon-right">
        <!-- Login link (when logged out) -->
        <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_new_donation_form.html.erb
<div style= "padding: 10px 20px;" >
  <%= simple_form_for [@ngo, @donation], remote: true do |f|  %>
  <%= @type.name %>
  <p><br>And provide us following information please:</p>
  <%= f.input :items %>
  <%= f.input :comments %>
  <%= f.input :type_id, as: :hidden, input_html: { value: params[:type_id] }%>
  <%= f.input :schedule, as: :string, input_html: { :class => "datepicker", :value => params[:date] }  %>
  <p><strong>Please select preferred time to Drop Off/ Pick Up</strong></p>

  <div class="input-group bootstrap-timepicker timepicker">
    <input id="timepicker1" type="text" class="form-control input-small">
    <span class="input-group-addon" value="From 9am to 7pm"><i class="glyphicon glyphicon-time" ></i></span>
  </div><br>


  <%= f.input :address, input_html: { value: @ngo.address } %>
  <%= f.submit class: 'btn btn-primary'%>
<% end %>
</div>

app/views/shared/_ngo_banner.html.erb
<div class="banner" alt= "responsive_image" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.3) 0%, rgba(0,0,0,0.1) 50%), url('<%= @ngo.photo %>'); height: 75vh; width:100%; background-position: center;">


  <div class="ngo-title-content">
    <h3 class="ngo-title"><%= @ngo.name.capitalize %></h3>
    <p class="ngo-quote">"We want to help you help others."</p>
  </div>
</div>

app/views/shared/_ngo_show_donation_form.html.erb
<%= form_tag(new_ngo_donation_path(ngo_id: @ngo.id), method: :get, class: "donation-form") do  %>

<% @ngo.types.each do |t| %>
<div class="ngo-type-donate-icons">
<%= radio_button_tag(:type_id, t.id, :required => true) %>
<%= label_tag(:type_id, image_tag("icons/#{t.name.downcase}.png"), class: "label-type-icon") %>
<%= label_tag(:type_id, t.name, class: "label-type-text") %>
</div>
<% end %>


<%= text_field_tag :date, nil, :class => "datepicker", :value => "Drop off/Pick up Date", :required => true %>

<%= submit_tag "Donate", class: "btn btn-primary" %>


<% end %>

app/views/shared/_ngo_show_map.html.erb
<div id="ngo-show-map"></div>


<% content_for(:after_js) do %>
  <script>
      styles = [
             {
                 "featureType": "all",
                 "elementType": "labels.text.fill",
                 "stylers": [
                     {
                         "saturation": 36
                     },
                     {
                         "color": "#333333"
                     },
                     {
                         "lightness": 40
                     }
                 ]
             },
             {
                 "featureType": "all",
                 "elementType": "labels.text.stroke",
                 "stylers": [
                     {
                         "visibility": "on"
                     },
                     {
                         "color": "#ffffff"
                     },
                     {
                         "lightness": 16
                     }
                 ]
             },
             {
                 "featureType": "all",
                 "elementType": "labels.icon",
                 "stylers": [
                     {
                         "visibility": "off"
                     }
                 ]
             },
             {
                 "featureType": "administrative",
                 "elementType": "geometry.fill",
                 "stylers": [
                     {
                         "color": "#fefefe"
                     },
                     {
                         "lightness": 20
                     }
                 ]
             },
             {
                 "featureType": "administrative",
                 "elementType": "geometry.stroke",
                 "stylers": [
                     {
                         "color": "#fefefe"
                     },
                     {
                         "lightness": 17
                     },
                     {
                         "weight": 1.2
                     }
                 ]
             },
             {
                 "featureType": "landscape",
                 "elementType": "geometry",
                 "stylers": [
                     {
                         "color": "#f5f5f5"
                     },
                     {
                         "lightness": 20
                     }
                 ]
             },
             {
                 "featureType": "poi",
                 "elementType": "geometry",
                 "stylers": [
                     {
                         "color": "#f5f5f5"
                     },
                   {
                       "lightness": 21
                   }
               ]
           },
             {
                 "featureType": "poi.park",
                 "elementType": "geometry",
                 "stylers": [
                     {
                         "color": "#dedede"
                     },
                     {
                         "lightness": 21
                     }
                 ]
             },
             {
                 "featureType": "road.highway",
                 "elementType": "geometry.fill",
                 "stylers": [
                     {
                         "color": "#ffffff"
                     },
                     {
                         "lightness": 17
                     }
                 ]
             },
             {
                 "featureType": "road.highway",
                 "elementType": "geometry.stroke",
                 "stylers": [
                     {
                         "color": "#ffffff"
                     },
                     {
                         "lightness": 29
                     },
                     {
                         "weight": 0.2
                     }
                 ]
             },
             {
                 "featureType": "road.arterial",
                 "elementType": "geometry",
                 "stylers": [
                     {
                         "color": "#ffffff"
                     },
                     {
                         "lightness": 18
                     }
                 ]
             },
             {
                 "featureType": "road.local",
                 "elementType": "geometry",
                 "stylers": [
                     {
                         "color": "#ffffff"
                     },
                     {
                         "lightness": 16
                     }
                 ]
             },
             {
                 "featureType": "transit",
                 "elementType": "geometry",
                 "stylers": [
                     {
                         "color": "#f2f2f2"
                     },
                     {
                         "lightness": 19
                     }
                 ]
             },
             {
                 "featureType": "water",
                 "elementType": "geometry",
                 "stylers": [
                     {
                         "color": "#e9e9e9"
                     },
                     {
                         "lightness": 17
                     }
                 ]
             },
             {
                 "featureType": "water",
                 "elementType": "geometry.fill",
                 "stylers": [
                     {
                         "saturation": "0"
                     },
                     {
                         "color": "#bab9b9"
                     }
                 ]
             }
         ]


    var handler = Gmaps.build('Google');

    var iconBase = 'http://res.cloudinary.com/dsmei8zni/image/upload/v1510754575/marker.png';


    handler.buildMap({
      internal: { id: 'ngo-show-map' }
    }, function() {
      markers = handler.addMarkers(<%= raw @hash.to_json %>);
      handler.bounds.extendWith(markers);

      handler.fitMapToBounds();

      if (markers.length == 0) {
        handler.getMap().setZoom(2);
      } else if (markers.length == 1) {
        handler.getMap().setZoom(14);
      }
    });
 </script>
<% end %>

app/views/shared/_searchbar.html.erb
<div class="form-inline">
<%= simple_form_for :ngos_path, method: :get do |f| %>
  <%= f.input :query, placeholder: 'Your favorite NGO', label: false %>
  <%= f.submit "search", class: 'btn btn-warning' %>
<% end %>
</div>

app/views/shared/_searchbar_navbar.html.erb
<div class="form-inline">
<%= simple_form_for :ngos_path, method: :get do |f| %>
  <%= f.input :query, placeholder: 'books', label: false %>
  <%= f.submit "search", class: 'btn btn-default' %>
<% end %>
</div>